In [1]:
# from syft import torch as th
# from syft import numpy as np
import torch as th
from syft._torch.tensor import AbstractTensor

In [4]:
x = AbstractTensor(AbstractTensor(th.tensor([[1],[2],[3],[4.,]], requires_grad=True)))
# x = AbstractTensor(AbstractTensor(th.tensor([[[[1],[2],[3],[4.,]]]], requires_grad=True)))
# x = AbstractTensor(AbstractTensor(th.tensor([[[[[[1],[2],[3],[4.,]]]]]], requires_grad=True)))
y = x + x



In [3]:
out = str(y)
out

'[AbstractTensor -> AbstractTensor -> tensor([[2.],\n        [4.],\n        [6.],\n        [8.]], grad_fn=<AddBackward0>)]'

In [4]:
type(x) == th.Tensor

False

In [4]:
x

[AbstractTensor -> [AbstractTensor -> tensor([1., 2., 3., 4.], requires_grad=True)]]

In [3]:
type(y).__name__

'AbstractTensor'

In [4]:
str(x)

'[AbstractTensor -> AbstractTensor -> Tensor]'

In [5]:
type(y)

torch.Tensor

In [12]:
y = x.mm(x)
y.backward(y)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [23]:
x.grad

tensor([[ 79., 137.],
        [133., 241.]])

In [8]:
type(x)

syft._torch.tensor.abstract.AbstractTorchTensor

In [12]:
x.child

tensor([1., 2., 3., 4.], requires_grad=True)

In [13]:
y

tensor([2., 4., 6., 8.])

In [7]:
x = th.tensor([1,2,3,4])

tensor([1, 2, 3, 4])

In [52]:
import importchecker

In [53]:
importchecker

<module 'importchecker' from '/opt/miniconda3/envs/torch1.5/lib/python3.6/site-packages/importchecker/__init__.py'>

In [54]:
import tempfile

In [107]:
f = open('/Users/atrask/Laboratory/openmined/PySyft/syft/_torch/tensor/abstract.py')
output = f.read()
f.close()

In [108]:
from syft.generic.compiler.comment_overrides import unused_import_line_numbers

In [72]:




file_name.close()


TypeError: '_io.BufferedRandom' object is not callable

In [1]:
import syft as sy
from pprintast.pprintast import ppast

sy.compile_torch()
sy.compile_numpy()

Generic (precision.py) -> Torch (syft/_torch/tensor/precision.py)
Generic (abstract.py) -> Torch (syft/_torch/tensor/abstract.py)
Generic (util.py) -> Torch (syft/_torch/tensor/util.py)
Generic (restricted.py) -> Torch (syft/_torch/tensor/restricted.py)
Generic (precision.py) -> Numpy (syft/_numpy/tensor/precision.py)
Generic (abstract.py) -> Numpy (syft/_numpy/tensor/abstract.py)
Generic (util.py) -> Numpy (syft/_numpy/tensor/util.py)
Generic (restricted.py) -> Numpy (syft/_numpy/tensor/restricted.py)


In [2]:
import ast

from syft.generic import tensor

from syft.generic.compiler.generic import get_complier_resources
from syft.generic.compiler.util import write_ast_to_file
from syft.generic.compiler.transformers.naming import SyftToFrameworkNameTransformer
from syft.generic.compiler.transformers.framework_decorator import FrameworkSpecificMethodDecoratorFilter
from syft.generic.compiler.transformers.handle_transformer import DecoratorAwareFrameworkHandleTransformer

# generic tensor python files to compile into torch tensors
compile_modules = list(set(dir(tensor)) - tensor.do_not_compile_modules)

In [3]:
import numpy as np

In [4]:
syft2framework2method = {}
syft2framework2method['Torch'] = {}
syft2framework2method['Numpy'] = {}

syft2framework2method['Numpy']['mm'] = 'matmul'

class SyftToFrameworkMethodNameConverter(ast.NodeTransformer):
    """This decorator searches through functions and methods looking
    for occurrences of 'sy.' or 'syft.' and replaces them with the
    handle for the appropriate framework.
    
    Note: This decorator should only be run AFTER 
    FrameworkSpecificMethodDecoratorFilter has been run.
    
    """
    
    
    def __init__(self, framework):
        self.framework = framework

        # change imports from Syft -> Framework
    def visit_FunctionDef(self, node: ast.ImportFrom):
#         print(node.args.defaults)
#         print(node.args.kw_defaults)
        for arg in node.args.defaults:
            if(hasattr(arg, 'id')):
                print(arg.id)
                
#             print(dir(arg))
        return node


In [138]:


module_name="abstract"
framework = "Torch"

# Get Tensor AST and target folder
tree, target_folder = get_complier_resources(tensor, module_name, framework)

# Replace occurrences of "Syft"with "Torch"
tree = SyftToFrameworkNameTransformer(framework).visit(tree)
tree = FrameworkSpecificMethodDecoratorFilter(framework).visit(tree)
tree = DecoratorAwareFrameworkHandleTransformer(framework).visit(tree)
tree = SyftToFrameworkMethodNameConverter(framework).visit(tree)

write_ast_to_file(tree, target_folder, module_name)

Generic (abstract.py) -> Torch (syft/_torch/tensor/abstract.py)
AbstractSyftTensor


In [108]:

ppast(tree)

Module(body=[
    ImportFrom(module='syft._torch.tensor.util', names=[
        alias(name='override_torch_function', asname=None),
      ], level=0),
    ImportFrom(module='syft._torch.tensor.util', names=[
        alias(name='torch_only', asname=None),
      ], level=0),
    ImportFrom(module='syft._torch.tensor.util', names=[
        alias(name='numpy_only', asname=None),
      ], level=0),
    ImportFrom(module='syft._torch.tensor.restricted', names=[
        alias(name='RestrictedTorchTensor', asname=None),
      ], level=0),
    Import(names=[
        alias(name='syft', asname='sy'),
      ]),
    Import(names=[
        alias(name='torch', asname='th'),
      ]),
    Import(names=[
        alias(name='numpy', asname='np'),
      ]),
    Assign(targets=[
        Name(id='HANDLED_FUNCTIONS_ABSTRACT', ctx=Store()),
      ], value=Dict(keys=[], values=[])),
    ClassDef(name='AbstractTorchTensor', bases=[
        Name(id='RestrictedTorchTensor', ctx=Load()),
      ], keywords=[], body

NameError: name 'ast' is not defined

In [40]:
import ast



In [22]:

x = th.FixedPrecisionTensor([[1,2],[3,4]]).set(extra="high five")

making abstract tensor


In [17]:
x

tensor([[1000., 2000.],
        [3000., 4000.]])

In [18]:
x.extra

'high five'

In [19]:
x.precision_fractional

3

In [20]:
x.base

10

In [ ]:
# th.tensor([1,2,3]).fix_precision(asdfasdfajsf)

In [4]:
type(x)

NoneType

In [5]:
type(x.data)

getset_descriptor

In [2]:
x

tensor([[1., 2.],
        [3., 4.]])

In [15]:
import torch as th

In [23]:
setattr(th.Tensor, "hey", "ho")

In [24]:
x = th.Tensor([1,2,3])

In [25]:
x.hey

'ho'

In [8]:
out

tensor([[2., 4.],
        [6., 8.]])

making subtensor


syft.tensor.abstract.AbstractTensor

In [5]:
out

tensor([[ 7., 10.],
        [15., 22.]])

In [6]:
x + x

making subtensor


tensor([[2., 4.],
        [6., 8.]])