In [1]:
import tensorflow as _tf
from syft.tensor import tensorflow as tf

# Tensorflow Eager Wishlist:

- build something which feels like you're subclassing tensorflow even if you're not
- GPU support
- autograd support

In [2]:
# class FixedPrecisionTensor(AbstractTorchTensor):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)

#         self.base = 10
#         self.precision_fractional = 3

#         self.data = self.data * self.scaling_factor

#     @property
#     def scaling_factor(self):
#         return self.base ** self.precision_fractional


In [3]:
w = tf.Variable([[100.0]]).on(tf.MinusIsMultiplyTensor).on(tf.PlusIsMinusTensor)

In [4]:
# w = tf.Variable([[100.0]]).on(tf.AbstractTensor)

In [5]:
# out = w@w

In [6]:
w + w

running __add__
running __mul__


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[10000.]], dtype=float32)>

In [7]:

# w = ResourceVariable([[100.0]])
with _tf.GradientTape() as tape:
    loss = w + w

grad = tape.gradient(loss, w)

running __add__
running __mul__


In [8]:
grad

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>

In [9]:
loss

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[10000.]], dtype=float32)>