In [1]:
import tensorflow as _tf
from syft.tensor import tensorflow as tf

# Tensorflow Eager Wishlist:

- build something which feels like you're subclassing tensorflow even if you're not
- GPU support
- autograd support

In [2]:
# class FixedPrecisionTensor(AbstractTorchTensor):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)

#         self.base = 10
#         self.precision_fractional = 3

#         self.data = self.data * self.scaling_factor

#     @property
#     def scaling_factor(self):
#         return self.base ** self.precision_fractional


In [5]:
w = tf.Variable([[100.0]]).on(tf.MinusIsMultiplyTensor).on(tf.PlusIsMinusTensor)
# x = tf.Variable([[1, 2], [3, 4]]).on(tf.AbstractTensor)

In [4]:
y = 2 + 2

NameError: name 'x' is not defined

In [16]:
out = w@w

In [17]:
out

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[10000.]], dtype=float32)>

In [15]:
w + w

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[200.]], dtype=float32)>

In [10]:

# w = ResourceVariable([[100.0]])
with _tf.GradientTape() as tape:
    loss = w + w

grad = tape.gradient(loss, w)

In [11]:
grad

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>

In [12]:
loss

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[10000.]], dtype=float32)>